### ISSUE TITLE
No module named 'olefile'

### ISSUE THREAD

**Issue by pmay** [openpreserve/carrus#17]
Problem when trying to identify a file using FIDO ('pronom only' action).

Results in following traceback:

> Traceback (most recent call last): File "C:\Users\pmay\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 193, in _run_module_as_main return _run_code(code, main_globals, None, File "C:\Users\pmay\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 86, in _run_code exec(code, run_globals) File "C:\Users\pmay\AppData\Local\Programs\OPF Carrus\resources\libs\fido\fido\fido.py", line 31, in <module> from .package import OlePackage, ZipPackage File "C:\Users\pmay\AppData\Local\Programs\OPF Carrus\resources\libs\fido\fido\package.py", line 6, in <module> import olefile ModuleNotFoundError: No module named 'olefile'

**Comment by bitsgalore** [comment]
Got that as well, see https://github.com/openpreserve/carrus/issues/18

**Comment by bdoubrov** [comment]
From the FIDO readme:

>FIDO 1.3.4 and later requires the python dependency 'olefile'. This can be installed using pip install olefile, by running python setup.py install, or a pip installation will handle dependencies.

Currently OPF Carrus doesn't run this setup.py at the install time. To be fixed.
